package gui;

import app.TargetHelper;
import app.TargetPractice;
import com.alee.managers.popup.PopupStyle;
import com.alee.managers.popup.WebPopup;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;

/**
 * Created with IntelliJ IDEA.
 * User: steffenwitt
 * Date: 02.01.13
 * Time: 21:37
 * To change this template use File | Settings | File Templates.
 */
public class TargetPracticePanel {
    private JTextField textField1;
    private JButton okButton;
    private JPanel targetPracticePanel;
    private JLabel hprTodayLabel;
    private JLabel hprTotalLabel;

    private JLabel hprLabel;
    private JComboBox targetBox;
    private JButton beendenButton;
    private TargetPractice associateGame;
    WebPopup wrongInputPopup = new WebPopup();


    public TargetPracticePanel() {
        wrongInputPopup.setSize(300, 50);
        wrongInputPopup.add(new JLabel("<html><font color='white'>Nur Zahlen zwischen 1 und 12 gültig</font></html>"));
        wrongInputPopup.setPopupStyle(PopupStyle.gray);
        textField1.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER)
                    sendThrow();
            }
        });
        okButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                sendThrow();
            }
        });
        associateGame = new TargetPractice();
        targetBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                hprLabel.setText("");
            }
        });
        beendenButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                associateGame.saveGame();
            }
        });
    }

    private void sendThrow() {
        try {
            int numOfHits = Integer.parseInt(textField1.getText());
            if (numOfHits < 0 || numOfHits > 12) {
                wrongInputPopup.showPopup(okButton);
            } else {
                wrongInputPopup.hidePopup();
                updateGui(associateGame.addThrow(numOfHits, targetBox.getSelectedItem().toString()));

            }
            textField1.setText("");


        } catch (NumberFormatException e) {
            wrongInputPopup.showPopup(okButton);

        }
    }

    private void updateGui(TargetHelper targetHelper) {
        DecimalFormat twoDForm = new DecimalFormat("#.##");
        hprLabel.setText("" + Double.valueOf(twoDForm.format(targetHelper.getHpr())));
    }


    public JPanel getTargetPracticePanel() {


        return targetPracticePanel;
    }

    public JTextField getTextField1() {
        return textField1;
    }

    public void setTextField1(JTextField textField1) {
        this.textField1 = textField1;
    }

    public JLabel getHprTodayLabel() {
        return hprTodayLabel;
    }

    public void setHprTodayLabel(JLabel hprTodayLabel) {
        this.hprTodayLabel = hprTodayLabel;
    }

    public JLabel getHprTotalLabel() {
        return hprTotalLabel;
    }

    public void setHprTotalLabel(JLabel hprTotalLabel) {
        this.hprTotalLabel = hprTotalLabel;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        targetPracticePanel = new JPanel();
        targetPracticePanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setFont(new Font(label1.getFont().getName(), label1.getFont().getStyle(), 28));
        label1.setText("Zu werfen:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        targetPracticePanel.add(label1, gbc);
        textField1 = new JTextField();
        textField1.setFont(new Font(textField1.getFont().getName(), textField1.getFont().getStyle(), 24));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        targetPracticePanel.add(textField1, gbc);
        final JLabel label2 = new JLabel();
        label2.setFont(new Font(label2.getFont().getName(), label2.getFont().getStyle(), 24));
        label2.setText("Anzahl Treffer:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        targetPracticePanel.add(label2, gbc);
        okButton = new JButton();
        okButton.setFont(new Font(okButton.getFont().getName(), okButton.getFont().getStyle(), 28));
        okButton.setText("OK");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        targetPracticePanel.add(okButton, gbc);
        final JLabel label3 = new JLabel();
        label3.setFont(new Font(label3.getFont().getName(), Font.BOLD, 28));
        label3.setHorizontalAlignment(0);
        label3.setHorizontalTextPosition(0);
        label3.setText("Target Practice");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        targetPracticePanel.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setFont(new Font(label4.getFont().getName(), label4.getFont().getStyle(), 28));
        label4.setText("HPR:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        targetPracticePanel.add(label4, gbc);
        final JSeparator separator1 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 0, 10, 0);
        targetPracticePanel.add(separator1, gbc);
        final JSeparator separator2 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.BOTH;
        targetPracticePanel.add(separator2, gbc);
        hprLabel = new JLabel();
        hprLabel.setFont(new Font(hprLabel.getFont().getName(), hprLabel.getFont().getStyle(), 28));
        hprLabel.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        targetPracticePanel.add(hprLabel, gbc);
        targetBox = new JComboBox();
        targetBox.setFont(new Font(targetBox.getFont().getName(), targetBox.getFont().getStyle(), 28));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        targetPracticePanel.add(targetBox, gbc);
        final JSeparator separator3 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.BOTH;
        targetPracticePanel.add(separator3, gbc);
        beendenButton = new JButton();
        beendenButton.setText("Beenden");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        targetPracticePanel.add(beendenButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return targetPracticePanel;
    }
}
