CREATE TABLE RTWSIMPLE
   (
      PLAYERNAME VARCHAR(24) NOT NULL ,
      GAMEID INTEGER NOT NULL,
      GAMEDATE DATE
      ONE INTEGER,
      TWO INTEGER,
      THREE INTEGER,
      FOUR INTEGER,
      FIVE INTEGER,
      SIX INTEGER,
      SEVEN INTEGER,
      EIGHT INTEGER,
      NINE INTEGER,
      TEN INTEGER,
      ELEVEN INTEGER,
      TWELVE INTEGER,
      THIRTEEN INTEGER,
      FOURTEEN INTEGER,
      FIVETEEN INTEGER,
      SIXTEEN INTEGER,
      SEVENTEEN INTEGER,
      EIGHTEEN INTEGER,
      NINETEEN INTEGER,
      TWENTY INTEGER
      BULL INTEGER,
   );


ALTER TABLE RTWSIMPLE
   ADD CONSTRAINT GAMEID Primary Key (
      RTWSIMPLE);

-- \************************************************************\


CREATE TABLE RTWBIG
   (
      PLAYERNAME VARCHAR(24) NOT NULL ,
      GAMEID INTEGER NOT NULL,
      GAMEDATE DATE
      ONE INTEGER,
      TWO INTEGER,
      THREE INTEGER,
      FOUR INTEGER,
      FIVE INTEGER,
      SIX INTEGER,
      SEVEN INTEGER,
      EIGHT INTEGER,
      NINE INTEGER,
      TEN INTEGER,
      ELEVEN INTEGER,
      TWELVE INTEGER,
      THIRTEEN INTEGER,
      FOURTEEN INTEGER,
      FIVETEEN INTEGER,
      SIXTEEN INTEGER,
      SEVENTEEN INTEGER,
      EIGHTEEN INTEGER,
      NINETEEN INTEGER,
      TWENTY INTEGER
      BULL INTEGER,
   );


ALTER TABLE RTWBIG
   ADD CONSTRAINT GAMEID Primary Key (
      RTWBIG);

-- \************************************************************\

CREATE TABLE RTWSMALL
   (
      PLAYERNAME VARCHAR(24) NOT NULL ,
      GAMEID INTEGER NOT NULL,
      GAMEDATE DATE
      ONE INTEGER,
      TWO INTEGER,
      THREE INTEGER,
      FOUR INTEGER,
      FIVE INTEGER,
      SIX INTEGER,
      SEVEN INTEGER,
      EIGHT INTEGER,
      NINE INTEGER,
      TEN INTEGER,
      ELEVEN INTEGER,
      TWELVE INTEGER,
      THIRTEEN INTEGER,
      FOURTEEN INTEGER,
      FIVETEEN INTEGER,
      SIXTEEN INTEGER,
      SEVENTEEN INTEGER,
      EIGHTEEN INTEGER,
      NINETEEN INTEGER,
      TWENTY INTEGER
      BULL INTEGER,
   );


ALTER TABLE RTWSMALL
   ADD CONSTRAINT GAMEID Primary Key (
      RTWSMALL);

-- \************************************************************\

CREATE TABLE RTWDOUBLE
   (
      PLAYERNAME VARCHAR(24) NOT NULL ,
      GAMEID INTEGER NOT NULL,
      GAMEDATE DATE
      ONE INTEGER,
      TWO INTEGER,
      THREE INTEGER,
      FOUR INTEGER,
      FIVE INTEGER,
      SIX INTEGER,
      SEVEN INTEGER,
      EIGHT INTEGER,
      NINE INTEGER,
      TEN INTEGER,
      ELEVEN INTEGER,
      TWELVE INTEGER,
      THIRTEEN INTEGER,
      FOURTEEN INTEGER,
      FIVETEEN INTEGER,
      SIXTEEN INTEGER,
      SEVENTEEN INTEGER,
      EIGHTEEN INTEGER,
      NINETEEN INTEGER,
      TWENTY INTEGER
      BULL INTEGER,
   );


ALTER TABLE RTWDOUBLE
   ADD CONSTRAINT GAMEID Primary Key (
      RTWDOUBLE);

-- \************************************************************\
CREATE TABLE RTWTRIPLE
   (
      PLAYERNAME VARCHAR(24) NOT NULL ,
      GAMEID INTEGER NOT NULL,
      GAMEDATE DATE
      ONE INTEGER,
      TWO INTEGER,
      THREE INTEGER,
      FOUR INTEGER,
      FIVE INTEGER,
      SIX INTEGER,
      SEVEN INTEGER,
      EIGHT INTEGER,
      NINE INTEGER,
      TEN INTEGER,
      ELEVEN INTEGER,
      TWELVE INTEGER,
      THIRTEEN INTEGER,
      FOURTEEN INTEGER,
      FIVETEEN INTEGER,
      SIXTEEN INTEGER,
      SEVENTEEN INTEGER,
      EIGHTEEN INTEGER,
      NINETEEN INTEGER,
      TWENTY INTEGER
      BULL INTEGER,
   );


ALTER TABLE RTWTRIPLE
   ADD CONSTRAINT GAMEID Primary Key (
      RTWTRIPLE);

-- \************************************************************\

